# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: file_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'file_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x66ile_service.proto\x12\x0b\x66ileservice\"/\n\rCreateRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"2\n\x0e\x43reateResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1f\n\x0bOpenRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\">\n\x0cOpenResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\x0f\n\x07message\x18\x03 \x01(\t\"/\n\rUploadRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"2\n\x0eUploadResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xdc\x01\n\x0b\x46ileService\x12\x45\n\nCreateFile\x12\x1a.fileservice.CreateRequest\x1a\x1b.fileservice.CreateResponse\x12?\n\x08OpenFile\x12\x18.fileservice.OpenRequest\x1a\x19.fileservice.OpenResponse\x12\x45\n\nUploadFile\x12\x1a.fileservice.UploadRequest\x1a\x1b.fileservice.UploadResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEREQUEST']._serialized_start=35
  _globals['_CREATEREQUEST']._serialized_end=82
  _globals['_CREATERESPONSE']._serialized_start=84
  _globals['_CREATERESPONSE']._serialized_end=134
  _globals['_OPENREQUEST']._serialized_start=136
  _globals['_OPENREQUEST']._serialized_end=167
  _globals['_OPENRESPONSE']._serialized_start=169
  _globals['_OPENRESPONSE']._serialized_end=231
  _globals['_UPLOADREQUEST']._serialized_start=233
  _globals['_UPLOADREQUEST']._serialized_end=280
  _globals['_UPLOADRESPONSE']._serialized_start=282
  _globals['_UPLOADRESPONSE']._serialized_end=332
  _globals['_FILESERVICE']._serialized_start=335
  _globals['_FILESERVICE']._serialized_end=555
# @@protoc_insertion_point(module_scope)
